# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bce0064b2ac5fb0e5388011a044b4b01350603c42ef8578a54bb6b99d4d8165eb10b0d5d93be16d0fce21255c59e1cca9d51c70aec21e181f01890873540b7c

test:
  secret_key_base: ef5420781c17347f6c90b258fe82cda544212353cda9beb9aaf26977cfa7359fc97dd169ae40ee649a3d9c3bf8c6f745a14f006f37930a5db059f15081ca53b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
